services:
  - type: web
    name: broke-n-built-services
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production

      - key: SESSION_SECRET
        sync: false

      - key: OPENAI_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      # PostgreSQL — created on Render and auto-injected into connected services
      - key: DATABASE_URL
        sync: false
